export const API = {
  test: "/test",
  tags: {
    findAll: "/tags",
    findById: "/tags/:id",
    create: "/tags",
    update: "/tags/:id",
    delete: "/tags/:id",
    findByField: "/tags/field/:fieldId",
    findByCompany: "/tags/company/:companyId",
    findByHackathon: "/tags/hackathon/:hackathonId",
    findByChallenge: "/tags/challenge/:challengeId",
    findByStudent: "/tags/student/:studentId",
  },
  students: {
    findAll: "/students",
    findById: "/students/:id",
    create: "/students",
    update: "/students/:id",
    delete: "/students/:id",
    findByField: "/students/field/:fieldId",
    findByRanking: "/students/ranking/:rankId",
    enrollCourse: "/students/:id/courses/:courseId/enroll",
    unenrollCourse: "/students/:id/courses/:courseId/unenroll",
    registerHackathon: "/students/:id/hackathons/:hackathonId/register",
    unregisterHackathon: "/students/:id/hackathons/:hackathonId/unregister",
    registerChallenge: "/students/:id/challenges/:challengeId/register",
    unregisterChallenge: "/students/:id/challenges/:challengeId/unregister",
  },
  rankings: {
    findAll: "/rankings",
    findById: "/rankings/:id",
    create: "/rankings",
    update: "/rankings/:id",
    delete: "/rankings/:id",
  },
  fields: {
    findAll: "/fields",
    findById: "/fields/:id",
    create: "/fields",
    update: "/fields/:id",
    delete: "/fields/:id",
    findAllSub: "/fields/:id/subfields",
  },
  hackathons: {
    findAll: "/hackathons",
    findById: "/hackathons/:id",
    create: "/hackathons",
    update: "/hackathons/:id",
    delete: "/hackathons/:id",
    findByCompany: "/hackathons/company/:companyId",
    findByChallenge: "/hackathons/challenge/:challengeId",
    findByStudent: "/hackathons/student/:studentId",
  },
  challenges: {
    findAll: "/challenges",
    findById: "/challenges/:id",
    create: "/challenges",
    update: "/challenges/:id",
    delete: "/challenges/:id",
    findByCompany: "/challenges/company/:companyId",
    findByHackathon: "/challenges/hackathon/:hackathonId",
    findByStudent: "/challenges/student/:studentId",
    findSubmissions: "/challenges/:id/submissions",
    submit: "/challenges/:id/submit",
    updateSubmission: "/challenges/submission/:submissionId/status",
    getAllSubmissions: "/challenges/submissions/all",
    getSubmissionById: "/challenges/submissions/:submissionId",
  },
  courses: {
    findAll: "/courses",
    findById: "/courses/:id",
    create: "/courses",
    update: "/courses/:id",
    delete: "/courses/:id",
    findByCompany: "/courses/company/:companyId",
    findStudents: "/courses/:id/students",
    enrollStudent: "/courses/:id/enroll/:studentId",
    unenrollStudent: "/courses/:id/unenroll/:studentId",
  },
  companies: {
    findAll: "/companies",
    findById: "/companies/:id",
    create: "/companies",
    update: "/companies/:id",
    delete: "/companies/:id",
    findHackathons: "/companies/:id/hackathons",
    findChallenges: "/companies/:id/challenges",
    findCourses: "/companies/:id/courses",
  },
  submissions: {
    findAll: "/submissions",
    findById: "/submissions/:id",
  },
};
